[binaries]
# 注意：需要设置 ANDROID_NDK_ROOT 环境变量
c = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang']
cpp = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++']
ar = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar']
strip = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip']

[built-in options]
c_args = ['-fPIC']
c_link_args = ['-Wl,-z,max-page-size=16384']

[properties]
android_abi = 'armeabi-v7a'

[host_machine]
system = 'android'
cpu_family = 'arm'
cpu = 'armv7a'
endian = 'little'