[binaries]
# 使用环境变量 ANDROID_NDK_ROOT
c = 'aarch64-linux-android21-clang'
cpp = 'aarch64-linux-android21-clang++'
ar = 'llvm-ar'
strip = 'llvm-strip'

[built-in options]
c_args = ['-fPIC']
c_link_args = ['-Wl,-z,max-page-size=16384']

[properties]
android_abi = 'arm64-v8a'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'