[binaries]
# 注意：需要设置 ANDROID_NDK_ROOT 环境变量
c = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang']
cpp = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang++']
ar = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar']
strip = ['$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip']

[built-in options]
c_args = ['-fPIC']
c_link_args = ['-Wl,-z,max-page-size=16384']

[properties]
android_abi = 'x86'

[host_machine]
system = 'android'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'