#!/usr/bin/env sed -i '' -f
# sed script to add cr_ prefix to SQLite functions from unity_required_symbols.txt
# Usage: sed -i '' -f add_cr_prefix_fixed.sed Plugins/sqlite-amalgamation/sqlite3.h
#        sed -i '' -f add_cr_prefix_fixed.sed Plugins/sqlite-amalgamation/sqlite3.c

# First, fix any double prefixes
s/cr_cr_sqlite3_/cr_sqlite3_/g

# Replace function declarations and definitions
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)sqlite3_backup_finish(/\1cr_sqlite3_backup_finish(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_backup_init\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_backup_step\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_blob\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_double\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_int\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_int64\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_null\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_parameter_index\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_bind_text16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_busy_timeout\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_changes\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_close\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_close_v2\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_blob\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_bytes\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_bytes16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_count\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_double\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_int\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_int64\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_name\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_name16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_text\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_text16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_column_type\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_config\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_deserialize\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_enable_load_extension\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_errcode\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_errmsg16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_extended_errcode\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_finalize\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_free\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_initialize\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_last_insert_rowid\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_libversion_number\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_malloc\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_malloc64\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_open\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_open_v2\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_open16\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_prepare_v2\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_realloc\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_realloc64\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_reset\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_serialize\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_shutdown\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_step\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_threadsafe\)(/\1cr_\2(/g
s/\(SQLITE_API[[:space:]]\+[^[:space:]]\+[[:space:]]\+\)\(sqlite3_win32_set_directory\)(/\1cr_\2(/g

# Replace function calls (not preceded by SQLITE_API)
s/\([^A-Za-z0-9_]\)\(sqlite3_backup_finish\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_backup_init\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_backup_step\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_blob\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_double\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_int\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_int64\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_null\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_parameter_index\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_bind_text16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_busy_timeout\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_changes\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_close\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_close_v2\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_blob\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_bytes\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_bytes16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_count\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_double\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_int\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_int64\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_name\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_name16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_text\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_text16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_column_type\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_config\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_deserialize\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_enable_load_extension\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_errcode\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_errmsg16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_extended_errcode\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_finalize\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_free\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_initialize\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_last_insert_rowid\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_libversion_number\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_malloc\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_malloc64\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_open\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_open_v2\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_open16\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_prepare_v2\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_realloc\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_realloc64\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_reset\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_serialize\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_shutdown\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_step\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_threadsafe\)(/\1cr_\2(/g
s/\([^A-Za-z0-9_]\)\(sqlite3_win32_set_directory\)(/\1cr_\2(/g

# Replace function names at the beginning of lines
s/^\(sqlite3_backup_finish\)/cr_\1/g
s/^\(sqlite3_backup_init\)/cr_\1/g
s/^\(sqlite3_backup_step\)/cr_\1/g
s/^\(sqlite3_bind_blob\)/cr_\1/g
s/^\(sqlite3_bind_double\)/cr_\1/g
s/^\(sqlite3_bind_int\)/cr_\1/g
s/^\(sqlite3_bind_int64\)/cr_\1/g
s/^\(sqlite3_bind_null\)/cr_\1/g
s/^\(sqlite3_bind_parameter_index\)/cr_\1/g
s/^\(sqlite3_bind_text16\)/cr_\1/g
s/^\(sqlite3_busy_timeout\)/cr_\1/g
s/^\(sqlite3_changes\)/cr_\1/g
s/^\(sqlite3_close\)/cr_\1/g
s/^\(sqlite3_close_v2\)/cr_\1/g
s/^\(sqlite3_column_blob\)/cr_\1/g
s/^\(sqlite3_column_bytes\)/cr_\1/g
s/^\(sqlite3_column_bytes16\)/cr_\1/g
s/^\(sqlite3_column_count\)/cr_\1/g
s/^\(sqlite3_column_double\)/cr_\1/g
s/^\(sqlite3_column_int\)/cr_\1/g
s/^\(sqlite3_column_int64\)/cr_\1/g
s/^\(sqlite3_column_name\)/cr_\1/g
s/^\(sqlite3_column_name16\)/cr_\1/g
s/^\(sqlite3_column_text\)/cr_\1/g
s/^\(sqlite3_column_text16\)/cr_\1/g
s/^\(sqlite3_column_type\)/cr_\1/g
s/^\(sqlite3_config\)/cr_\1/g
s/^\(sqlite3_deserialize\)/cr_\1/g
s/^\(sqlite3_enable_load_extension\)/cr_\1/g
s/^\(sqlite3_errcode\)/cr_\1/g
s/^\(sqlite3_errmsg16\)/cr_\1/g
s/^\(sqlite3_extended_errcode\)/cr_\1/g
s/^\(sqlite3_finalize\)/cr_\1/g
s/^\(sqlite3_free\)/cr_\1/g
s/^\(sqlite3_initialize\)/cr_\1/g
s/^\(sqlite3_last_insert_rowid\)/cr_\1/g
s/^\(sqlite3_libversion_number\)/cr_\1/g
s/^\(sqlite3_malloc\)/cr_\1/g
s/^\(sqlite3_malloc64\)/cr_\1/g
s/^\(sqlite3_open\)/cr_\1/g
s/^\(sqlite3_open_v2\)/cr_\1/g
s/^\(sqlite3_open16\)/cr_\1/g
s/^\(sqlite3_prepare_v2\)/cr_\1/g
s/^\(sqlite3_realloc\)/cr_\1/g
s/^\(sqlite3_realloc64\)/cr_\1/g
s/^\(sqlite3_reset\)/cr_\1/g
s/^\(sqlite3_serialize\)/cr_\1/g
s/^\(sqlite3_shutdown\)/cr_\1/g
s/^\(sqlite3_step\)/cr_\1/g
s/^\(sqlite3_threadsafe\)/cr_\1/g
s/^\(sqlite3_win32_set_directory\)/cr_\1/g

# Replace function names used as function pointers (after comma or equals)
s/\([,=[:space:]]\)\(sqlite3_backup_finish\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_backup_init\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_backup_step\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_blob\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_double\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_int\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_int64\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_null\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_parameter_index\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_bind_text16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_busy_timeout\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_changes\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_close\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_close_v2\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_blob\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_bytes\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_bytes16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_count\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_double\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_int\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_int64\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_name\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_name16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_text\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_text16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_column_type\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_config\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_deserialize\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_enable_load_extension\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_errcode\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_errmsg16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_extended_errcode\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_finalize\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_free\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_initialize\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_last_insert_rowid\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_libversion_number\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_malloc\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_malloc64\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_open\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_open_v2\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_open16\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_prepare_v2\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_realloc\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_realloc64\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_reset\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_serialize\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_shutdown\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_step\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_threadsafe\)\([,;[:space:]]\)/\1cr_\2\3/g
s/\([,=[:space:]]\)\(sqlite3_win32_set_directory\)\([,;[:space:]]\)/\1cr_\2\3/g

# Replace function names as parameters (including parentheses)
s/\([,[:space:]]\)\(sqlite3_backup_finish\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_backup_init\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_backup_step\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_blob\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_double\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_int\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_int64\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_null\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_parameter_index\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_bind_text16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_busy_timeout\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_changes\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_close\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_close_v2\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_blob\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_bytes\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_bytes16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_count\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_double\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_int\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_int64\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_name\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_name16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_text\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_text16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_column_type\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_config\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_deserialize\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_enable_load_extension\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_errcode\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_errmsg16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_extended_errcode\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_finalize\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_free\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_initialize\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_last_insert_rowid\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_libversion_number\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_malloc\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_malloc64\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_open\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_open_v2\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_open16\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_prepare_v2\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_realloc\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_realloc64\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_reset\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_serialize\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_shutdown\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_step\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_threadsafe\)\()\)/\1cr_\2\3/g
s/\([,[:space:]]\)\(sqlite3_win32_set_directory\)\()\)/\1cr_\2\3/g

# Replace function names in comparisons and macro definitions
s/\(==\)\(sqlite3_backup_finish\)/\1cr_\2/g
s/\(==\)\(sqlite3_backup_init\)/\1cr_\2/g
s/\(==\)\(sqlite3_backup_step\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_blob\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_double\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_int\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_int64\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_null\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_parameter_index\)/\1cr_\2/g
s/\(==\)\(sqlite3_bind_text16\)/\1cr_\2/g
s/\(==\)\(sqlite3_busy_timeout\)/\1cr_\2/g
s/\(==\)\(sqlite3_changes\)/\1cr_\2/g
s/\(==\)\(sqlite3_close\)/\1cr_\2/g
s/\(==\)\(sqlite3_close_v2\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_blob\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_bytes\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_bytes16\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_count\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_double\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_int\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_int64\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_name\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_name16\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_text\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_text16\)/\1cr_\2/g
s/\(==\)\(sqlite3_column_type\)/\1cr_\2/g
s/\(==\)\(sqlite3_config\)/\1cr_\2/g
s/\(==\)\(sqlite3_deserialize\)/\1cr_\2/g
s/\(==\)\(sqlite3_enable_load_extension\)/\1cr_\2/g
s/\(==\)\(sqlite3_errcode\)/\1cr_\2/g
s/\(==\)\(sqlite3_errmsg16\)/\1cr_\2/g
s/\(==\)\(sqlite3_extended_errcode\)/\1cr_\2/g
s/\(==\)\(sqlite3_finalize\)/\1cr_\2/g
s/\(==\)\(sqlite3_free\)/\1cr_\2/g
s/\(==\)\(sqlite3_initialize\)/\1cr_\2/g
s/\(==\)\(sqlite3_last_insert_rowid\)/\1cr_\2/g
s/\(==\)\(sqlite3_libversion_number\)/\1cr_\2/g
s/\(==\)\(sqlite3_malloc\)/\1cr_\2/g
s/\(==\)\(sqlite3_malloc64\)/\1cr_\2/g
s/\(==\)\(sqlite3_open\)/\1cr_\2/g
s/\(==\)\(sqlite3_open_v2\)/\1cr_\2/g
s/\(==\)\(sqlite3_open16\)/\1cr_\2/g
s/\(==\)\(sqlite3_prepare_v2\)/\1cr_\2/g
s/\(==\)\(sqlite3_realloc\)/\1cr_\2/g
s/\(==\)\(sqlite3_realloc64\)/\1cr_\2/g
s/\(==\)\(sqlite3_reset\)/\1cr_\2/g
s/\(==\)\(sqlite3_serialize\)/\1cr_\2/g
s/\(==\)\(sqlite3_shutdown\)/\1cr_\2/g
s/\(==\)\(sqlite3_step\)/\1cr_\2/g
s/\(==\)\(sqlite3_threadsafe\)/\1cr_\2/g
s/\(==\)\(sqlite3_win32_set_directory\)/\1cr_\2/g

# Replace function names in macro definitions  
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_backup_finish\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_backup_init\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_backup_step\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_blob\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_double\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_int\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_int64\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_null\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_parameter_index\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_bind_text16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_busy_timeout\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_changes\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_close\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_close_v2\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_blob\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_bytes\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_bytes16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_count\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_double\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_int\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_int64\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_name\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_name16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_text\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_text16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_column_type\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_config\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_deserialize\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_enable_load_extension\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_errcode\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_errmsg16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_extended_errcode\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_finalize\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_free\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_initialize\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_last_insert_rowid\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_libversion_number\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_malloc\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_malloc64\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_open\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_open_v2\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_open16\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_prepare_v2\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_realloc\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_realloc64\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_reset\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_serialize\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_shutdown\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_step\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_threadsafe\)/\1cr_\2/g
s/\(#define[[:space:]]\+[A-Za-z_][A-Za-z0-9_]*[[:space:]]\+\)\(sqlite3_win32_set_directory\)/\1cr_\2/g

# Simple replacements for specific cases
s/sqlite3_free$/cr_sqlite3_free/g
